import './globals.css'
import '@mantine/core/styles.css'

import type { Metadata } from 'next'
import { ColorSchemeScript, MantineProvider } from '@mantine/core'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import { NerkoOne, Jost } from '@/app/lib/fonts'

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${NerkoOne.variable} ${Jost.variable} antialiased`}>
        <MantineProvider forceColorScheme="dark">{children}</MantineProvider>
      </body>
    </html>
  )
}
